[tox]
envlist =
    linting
    py39
    py310
    py311
    py312
    py313
    pypy3
skip_missing_interpreters = true

[testenv]
description = run tests
deps =
    -r requirements.txt
commands =
    pytest -vv {posargs}

[testenv:linting]
description = run linting
skip_install = true
deps =
    black
    flake8
    flake8-noqa
    isort
commands =
    black -t py39 -t py310 -t py311 -t py312 -t py313 --line-length=120 .
    isort --line-length=120 --profile=black --python-version=39 .
    flake8 --extend-exclude={env:VIRTUAL_ENV} --extend-ignore=E203 --max-line-length=120 .

[pytest]
testpaths = tests/
