# Tox (https://tox.wiki/) is a tool for running tests in multiple
# virtualenvs. This configuration file will run the test suite on all
# supported python versions. To use it, run "tox" from this directory.
#
# For a specific environment, run:
#     "tox -e <env>" (i.e.: "tox -e py313" or "tox -e lint")
#
# This tox configuration will skip any Python interpreters that can't be found.
# To manage multiple Python interpreters for covering all versions, you can use
# pyenv: https://github.com/pyenv/pyenv


[tox]
envlist =
    validate
    lint
    py39
    py310
    py311
    py312
    py313
    pypy3
skip_missing_interpreters = true


[testenv:validate]
description = validate project configuration
dependency_groups =
    validate
skip_install = true
commands =
    validate-pyproject pyproject.toml


[testenv:lint]
description = run linting and formatting
skip_install = true
dependency_groups =
    lint
commands =
    black -t py39 -t py310 -t py311 -t py312 -t py313 --line-length=120 .
    isort --line-length=120 --profile=black --python-version=39 .
    flake8 --extend-exclude={env:VIRTUAL_ENV} --extend-ignore=E203 --max-line-length=120 .


[testenv:lint-ci]
description = run linting and formatting for CI
skip_install = true
dependency_groups =
    lint
commands =
    black -t py39 -t py310 -t py311 -t py312 -t py313 --check --diff --line-length=120 .
    isort --line-length=120 --profile=black --python-version=39 .
    flake8 --extend-exclude={env:VIRTUAL_ENV} --extend-ignore=E203 --max-line-length=120 .


[testenv]
description = run tests
dependency_groups =
    test
commands =
    pytest -vv {posargs} tests/unit/
