[tox]
envlist = py{313,py3}{,-ansi2html}, linting
skip_missing_interpreters = true

[testenv]
setenv = PYTHONDONTWRITEBYTECODE=1
deps =
    -r requirements.txt
    py{313,py3}-ansi2html: ansi2html
commands = pytest -v -r a {posargs}

[testenv:linting]
skip_install = True
deps =
    flake8
    flake8-noqa
commands = flake8 --extend-exclude={env:VIRTUAL_ENV} .

[flake8]
max-line-length = 120

[pytest]
testpaths = tests/
