name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --group dev .
      - name: Run linters
        run: |
          source venv/bin/activate
          tox
        env:
          TOXENV: lint-ci
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --group dev .
      - name: Run tests
        run: |
          source venv/bin/activate
          tox
        env:
          TOXENV: py39
